// SQL codegen: feature spec → CREATE TABLE + RLS + indexes
// Follows conventions from docs/agents/schema.md

import type { FeatureSpec, ColumnSpec } from "./feature-schema.js";

const SQL_TYPE_MAP: Record<string, string> = {
  text: "TEXT",
  email: "TEXT",
  integer: "INTEGER",
  numeric: "NUMERIC(10,2)",
  boolean: "BOOLEAN DEFAULT false",
  date: "TIMESTAMPTZ",
  select: "TEXT",
};

function columnToSQL(col: ColumnSpec): string {
  let def = `    ${col.name} `;

  if (col.type === "select" && col.options!.length > 0) {
    const opts = col.options!.map((o) => `'${o}'`).join(", ");
    def += `TEXT CHECK (${col.name} IN (${opts}))`;
  } else {
    def += SQL_TYPE_MAP[col.type] ?? "TEXT";
  }

  if (col.required) def += " NOT NULL";
  if (col.default) {
    if (col.type === "boolean") {
      def += ""; // boolean already has DEFAULT false
    } else {
      def += ` DEFAULT '${col.default}'`;
    }
  }

  return def;
}

export function generateSchemaSQL(feature: FeatureSpec): string {
  const t = feature.table;
  const cols = feature.columns.map(columnToSQL).join(",\n");

  return `-- =============================================================
-- Feature: ${feature.name}
-- Generated by venture codegen — safe to customize after generation
-- =============================================================

CREATE TABLE IF NOT EXISTS ${t} (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
${cols},
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Row-Level Security
ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own ${t}" ON ${t}
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own ${t}" ON ${t}
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own ${t}" ON ${t}
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own ${t}" ON ${t}
    FOR DELETE USING (auth.uid() = user_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_${t}_user_id ON ${t}(user_id);
CREATE INDEX IF NOT EXISTS idx_${t}_created_at ON ${t}(created_at DESC);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER ${t}_updated_at
    BEFORE UPDATE ON ${t}
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
`;
}
